# importing libraries

In [1]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

# loading dataset

In [2]:
df = pd.read_csv('AmesHousing.csv')

In [3]:
df.head()

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,...,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
0,1,526301100,20,RL,141.0,31770,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,5,2010,WD,Normal,215000
1,2,526350040,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,...,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal,105000
2,3,526351010,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal,172000
3,4,526353030,20,RL,93.0,11160,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,244000
4,5,527105010,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,...,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal,189900

In [4]:
df.shape

(2930, 82)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2930 entries, 0 to 2929
Data columns (total 82 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order            2930 non-null   int64
 1   PID              2930 non-null   int64
 2   MS SubClass      2930 non-null   int64
 3   MS Zoning        2930 non-null   object
 4   Lot Frontage     2440 non-null   float64
 5   Lot Area         2930 non-null   int64
 6   Street           2930 non-null   object
 7   Alley            198 non-null    object
 8   Lot Shape        2930 non-null   object
 9   Land Contour     2930 non-null   object
 10  Utilities        2930 non-null   object
 11  Lot Config       2930 non-null   object
 12  Land Slope       2930 non-null   object
 13  Neighborhood     2930 non-null   object
 14  Condition 1      2930 non-null   object
 15  Condition 2      2930 non-null   object
 16  Bldg Type        2930 non-null   object
 17  House Style      2930 non-null   object
 18  Overall Qual     2930 non-null   int64
 19  Overall Cond     2930 non-null   int64
 20  Year Built       2930 non-null   int64
 21  Year Remod/Add   2930 non-null   int64
 22  Roof Style       2930 non-null   object
 23  Roof Matl        2930 non-null   object
 24  Exterior 1st     2930 non-null   object
 25  Exterior 2nd     2930 non-null   object
 26  Mas Vnr Type     1155 non-null   object
 27  Mas Vnr Area     2907 non-null   float64
 28  Exter Qual       2930 non-null   object
 29  Exter Cond       2930 non-null   object
 30  Foundation       2930 non-null   object
 31  Bsmt Qual        2850 non-null   object
 32  Bsmt Cond        2850 non-null   object
 33  Bsmt Exposure    2847 non-null   object
 34  BsmtFin Type 1   2850 non-null   object
 35  BsmtFin SF 1     2929 non-null   float64
 36  BsmtFin Type 2   2849 non-null   object
 37  BsmtFin SF 2     2929 non-null   float64
 38  Bsmt Unf SF      2929 non-null   float64
 39  Total Bsmt SF    2929 non-null   float64
 40  Heating          2930 non-null   object
 41  Heating QC       2930 non-null   object
 42  Central Air      2930 non-null   object
 43  Electrical       2929 non-null   object
 44  1st Flr SF       2930 non-null   int64
 45  2nd Flr SF       2930 non-null   int64
 46  Low Qual Fin SF  2930 non-null   int64
 47  Gr Liv Area      2930 non-null   int64
 48  Bsmt Full Bath   2928 non-null   float64
 49  Bsmt Half Bath   2928 non-null   float64
 50  Full Bath        2930 non-null   int64
 51  Half Bath        2930 non-null   int64
 52  Bedroom AbvGr    2930 non-null   int64
 53  Kitchen AbvGr    2930 non-null   int64
 54  Kitchen Qual     2930 non-null   object
 55  TotRms AbvGrd    2930 non-null   int64
 56  Functional       2930 non-null   object
 57  Fireplaces       2930 non-null   int64
 58  Fireplace Qu     1508 non-null   object
 59  Garage Type      2773 non-null   object
 60  Garage Yr Blt    2771 non-null   float64
 61  Garage Finish    2771 non-null   object
 62  Garage Cars      2929 non-null   float64
 63  Garage Area      2929 non-null   float64
 64  Garage Qual      2771 non-null   object
 65  Garage Cond      2771 non-null   object
 66  Paved Drive      2930 non-null   object
 67  Wood Deck SF     2930 non-null   int64
 68  Open Porch SF    2930 non-null   int64
 69  Enclosed Porch   2930 non-null   int64
 70  3Ssn Porch       2930 non-null   int64
 71  Screen Porch     2930 non-null   int64
 72  Pool Area        2930 non-null   int64
 73  Pool QC          13 non-null     object
 74  Fence            572 non-null    object
 75  Misc Feature     106 non-null    object
 76  Misc Val         2930 non-null   int64
 77  Mo Sold          2930 non-null   int64
 78  Yr Sold          2930 non-null   int64
 79  Sale Type        2930 non-null   object
 80  Sale Condition   2930 non-null   object
 81  SalePrice        2930 non-null   int64
dtypes: float64(11), int64(28), object(43)
memory usage: 1.8+ MB

# Checking missing values

In [6]:
col=[]
for i in df.columns:
    if df[i].isnull().sum() != 0:
        print(f'{i} ({df[i].dtypes}) : {df[i].isnull().sum()}')
        col.append(i)

Lot Frontage (float64) : 490
Alley (object) : 2732
Mas Vnr Type (object) : 1775
Mas Vnr Area (float64) : 23
Bsmt Qual (object) : 80
Bsmt Cond (object) : 80
Bsmt Exposure (object) : 83
BsmtFin Type 1 (object) : 80
BsmtFin SF 1 (float64) : 1
BsmtFin Type 2 (object) : 81
BsmtFin SF 2 (float64) : 1
Bsmt Unf SF (float64) : 1
Total Bsmt SF (float64) : 1
Electrical (object) : 1
Bsmt Full Bath (float64) : 2
Bsmt Half Bath (float64) : 2
Fireplace Qu (object) : 1422
Garage Type (object) : 157
Garage Yr Blt (float64) : 159
Garage Finish (object) : 159
Garage Cars (float64) : 1
Garage Area (float64) : 1
Garage Qual (object) : 159
Garage Cond (object) : 159
Pool QC (object) : 2917
Fence (object) : 2358
Misc Feature (object) : 2824

In [7]:
col

['Lot Frontage',
 'Alley',
 'Mas Vnr Type',
 'Mas Vnr Area',
 'Bsmt Qual',
 'Bsmt Cond',
 'Bsmt Exposure',
 'BsmtFin Type 1',
 'BsmtFin SF 1',
 'BsmtFin Type 2',
 'BsmtFin SF 2',
 'Bsmt Unf SF',
 'Total Bsmt SF',
 'Electrical',
 'Bsmt Full Bath',
 'Bsmt Half Bath',
 'Fireplace Qu',
 'Garage Type',
 'Garage Yr Blt',
 'Garage Finish',
 'Garage Cars',
 'Garage Area',
 'Garage Qual',
 'Garage Cond',
 'Pool QC',
 'Fence',
 'Misc Feature']

# Handling Missing values

In [8]:
for i in col:
    if df[i].dtypes == 'float64':
        df[i].fillna(df[i].mean(), inplace=True)
    if df[i].dtypes == 'object':
        df[i].fillna(df[i].mode()[0], inplace=True)

# Scaling the numerical data

In [9]:
numerical_cols = [cols for cols in df.select_dtypes(include=['int64','float64']).columns if cols!='SalePrice']
scaler = StandardScaler()
df[numerical_cols] = scaler.fit_transform(df[numerical_cols])

In [10]:
df.head()

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,...,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
0,-1.731460,-0.997164,-0.877005,RL,3.366911,2.744381,Pave,Grvl,IR1,Lvl,...,-0.063031,Ex,MnPrv,Shed,-0.089422,-0.448057,1.678499,WD,Normal,215000
1,-1.730277,-0.996904,-0.877005,RH,0.505463,0.187097,Pave,Grvl,Reg,Lvl,...,-0.063031,Ex,MnPrv,Shed,-0.089422,-0.079602,1.678499,WD,Normal,105000
2,-1.729095,-0.996899,-0.877005,RL,0.552372,0.522814,Pave,Grvl,IR1,Lvl,...,-0.063031,Ex,MnPrv,Gar2,21.985725,-0.079602,1.678499,WD,Normal,172000
3,-1.727913,-0.996888,-0.877005,RL,1.115280,0.128458,Pave,Grvl,Reg,Lvl,...,-0.063031,Ex,MnPrv,Shed,-0.089422,-0.816513,1.678499,WD,Normal,244000
4,-1.726731,-0.992903,0.061285,RL,0.224010,0.467348,Pave,Grvl,IR1,Lvl,...,-0.063031,Ex,MnPrv,Shed,-0.089422,-1.184969,1.678499,WD,Normal,189900

# Mapping of categorical data

In [11]:
columns_select = df.select_dtypes(include=['object','category']).columns

In [12]:
columns_select

Index(['MS Zoning', 'Street', 'Alley', 'Lot Shape', 'Land Contour',
       'Utilities', 'Lot Config', 'Land Slope', 'Neighborhood', 'Condition 1',
       'Condition 2', 'Bldg Type', 'House Style', 'Roof Style', 'Roof Matl',
       'Exterior 1st', 'Exterior 2nd', 'Mas Vnr Type', 'Exter Qual',
       'Exter Cond', 'Foundation', 'Bsmt Qual', 'Bsmt Cond', 'Bsmt Exposure',
       'BsmtFin Type 1', 'BsmtFin Type 2', 'Heating', 'Heating QC',
       'Central Air', 'Electrical', 'Kitchen Qual', 'Functional',
       'Fireplace Qu', 'Garage Type', 'Garage Finish', 'Garage Qual',
       'Garage Cond', 'Paved Drive', 'Pool QC', 'Fence', 'Misc Feature',
       'Sale Type', 'Sale Condition'],
      dtype='object')

In [13]:
for i in columns_select:
    mapping={}
    for idx, val in enumerate(df[i].unique()):
        mapping[val] = idx
    df[i] = df[i].map(mapping)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2930 entries, 0 to 2929
Data columns (total 82 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order            2930 non-null   float64
 1   PID              2930 non-null   float64
 2   MS SubClass      2930 non-null   float64
 3   MS Zoning        2930 non-null   int64
 4   Lot Frontage     2930 non-null   float64
 5   Lot Area         2930 non-null   float64
 6   Street           2930 non-null   int64
 7   Alley            2930 non-null   int64
 8   Lot Shape        2930 non-null   int64
 9   Land Contour     2930 non-null   int64
 10  Utilities        2930 non-null   int64
 11  Lot Config       2930 non-null   int64
 12  Land Slope       2930 non-null   int64
 13  Neighborhood     2930 non-null   int64
 14  Condition 1      2930 non-null   int64
 15  Condition 2      2930 non-null   int64
 16  Bldg Type        2930 non-null   int64
 17  House Style      2930 non-null   int64
 18  Overall Qual     2930 non-null   float64
 19  Overall Cond     2930 non-null   float64
 20  Year Built       2930 non-null   float64
 21  Year Remod/Add   2930 non-null   float64
 22  Roof Style       2930 non-null   int64
 23  Roof Matl        2930 non-null   int64
 24  Exterior 1st     2930 non-null   int64
 25  Exterior 2nd     2930 non-null   int64
 26  Mas Vnr Type     2930 non-null   int64
 27  Mas Vnr Area     2930 non-null   float64
 28  Exter Qual       2930 non-null   int64
 29  Exter Cond       2930 non-null   int64
 30  Foundation       2930 non-null   int64
 31  Bsmt Qual        2930 non-null   int64
 32  Bsmt Cond        2930 non-null   int64
 33  Bsmt Exposure    2930 non-null   int64
 34  BsmtFin Type 1   2930 non-null   int64
 35  BsmtFin SF 1     2930 non-null   float64
 36  BsmtFin Type 2   2930 non-null   int64
 37  BsmtFin SF 2     2930 non-null   float64
 38  Bsmt Unf SF      2930 non-null   float64
 39  Total Bsmt SF    2930 non-null   float64
 40  Heating          2930 non-null   int64
 41  Heating QC       2930 non-null   int64
 42  Central Air      2930 non-null   int64
 43  Electrical       2930 non-null   int64
 44  1st Flr SF       2930 non-null   float64
 45  2nd Flr SF       2930 non-null   float64
 46  Low Qual Fin SF  2930 non-null   float64
 47  Gr Liv Area      2930 non-null   float64
 48  Bsmt Full Bath   2930 non-null   float64
 49  Bsmt Half Bath   2930 non-null   float64
 50  Full Bath        2930 non-null   float64
 51  Half Bath        2930 non-null   float64
 52  Bedroom AbvGr    2930 non-null   float64
 53  Kitchen AbvGr    2930 non-null   float64
 54  Kitchen Qual     2930 non-null   int64
 55  TotRms AbvGrd    2930 non-null   float64
 56  Functional       2930 non-null   int64
 57  Fireplaces       2930 non-null   float64
 58  Fireplace Qu     2930 non-null   int64
 59  Garage Type      2930 non-null   int64
 60  Garage Yr Blt    2930 non-null   float64
 61  Garage Finish    2930 non-null   int64
 62  Garage Cars      2930 non-null   float64
 63  Garage Area      2930 non-null   float64
 64  Garage Qual      2930 non-null   int64
 65  Garage Cond      2930 non-null   int64
 66  Paved Drive      2930 non-null   int64
 67  Wood Deck SF     2930 non-null   float64
 68  Open Porch SF    2930 non-null   float64
 69  Enclosed Porch   2930 non-null   float64
 70  3Ssn Porch       2930 non-null   float64
 71  Screen Porch     2930 non-null   float64
 72  Pool Area        2930 non-null   float64
 73  Pool QC          2930 non-null   int64
 74  Fence            2930 non-null   int64
 75  Misc Feature     2930 non-null   int64
 76  Misc Val         2930 non-null   float64
 77  Mo Sold          2930 non-null   float64
 78  Yr Sold          2930 non-null   float64
 79  Sale Type        2930 non-null   int64
 80  Sale Condition   2930 non-null   int64
 81  SalePrice        2930 non-null   int64
dtypes: float64(38), int64(44)
memory usage: 1.8 MB

In [15]:
df.to_csv("cleaned_dataset.csv", index=False)